version: '2'
services:
    rcsihipster-app:
        image: rcsihipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://35.195.41.231:3306/rcsihipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=rcsihipster-elasticsearch:9300
        ports:
            - 8080:8080
    rcsihipster-mysql:
        extends:
            file: mysql.yml
            service: rcsihipster-mysql
    rcsihipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: rcsihipster-elasticsearch
